### ISSUE TITLE
Design Refresh

### ISSUE THREAD

**Issue by mattbrett** [awesomemotive/file-upload-types#22]
Hi @sanzeeb3, we're going to give the table on the settings page a visual refresh. Basically, we're looking to increase the contrast and make it easier to understand at a glance. Here's how it looks...

![fileuploadtypes-settings-200811@2x](https://user-images.githubusercontent.com/868109/90545901-2c8ecf00-e13e-11ea-98ae-050fc636c801.png)

And here's a breakdown of the changes...

- [x] Table heading background and border colour is now `#7d8992`. Text colour is `#ffffff`.

- [x] Table heading has top-left and top-right rounded corners, 4px.

- [x] Table heading has a very subtle dropshadow. Can you try this? `box-shadow: 0 1px 2px rgba(125, 137, 146, .15);`

- [x] Change all borders to `#ccd0d4`.

- [x] Subheadings background colour is now `#e7e8e7`. Text colour is `#444444`.

- [x] Info icon in the Add Custom File Types should now be #b5b6b5 and we need to make it a bit smaller. This will apply to the plus and trash icons as well, and that's fine. They're a bit off.

```
#file-upload-types .file-upload-types-content .file-upload-types-table .table-container table img {
    width: 14px;
    height: 14px;
    margin-bottom: -2px;
}
```

- [x] And lastly, the tooltip. Can you make sure its background is `#21282c`?

I think that's everything. Let me know if you have any questions.

**Comment by mattbrett** [comment]
@sanzeeb3 Looking good, but some changes still.

- [ ] Border colours across the entire table still need changed to `#ccd0d4`. Specifically...
**#file-upload-types .file-upload-types-content .file-upload-types-table .table-container table
#file-upload-types .file-upload-types-content .file-upload-types-table .table-container tr**

- [ ] Let's change the box-shadow on **#file-upload-types .file-upload-types-content .file-upload-types-table .table-container:nth-of-type(2) table** to `0 2px 4px rgba(0,0,0,0.15)`.

- [ ] Also on **#file-upload-types .file-upload-types-content .file-upload-types-table .table-container:nth-of-type(2) table** please add `margin-bottom: -1px;`.

- [ ] Can you add `text-align: right;` to the last column of the Add table at the bottom?

<img width="1190" alt="CleanShot 2020-08-28 at 11 48 14@2x" src="https://user-images.githubusercontent.com/868109/91605399-4346da00-e925-11ea-86bc-780bee5f519a.png">

- [ ] We've been improving our focus states in other plugins, and I'll like to do that here as well. Input fields are good, but we need to improve the button. For it's focus state, please add `box-shadow: 0 0 0 1px #fff, 0 0 0 3px #c45e1b;` Please apply this to all of the button colours we have for this plugin. I know there's the blue one in the header, but not sure if there are others.

<img width="142" alt="CleanShot 2020-08-28 at 11 54 06@2x" src="https://user-images.githubusercontent.com/868109/91605454-55c11380-e925-11ea-8349-42c7e49e19c3.png">

<img width="325" alt="CleanShot 2020-08-28 at 11 57 10@2x" src="https://user-images.githubusercontent.com/868109/91605663-aafd2500-e925-11ea-98bf-133f0817ff46.png">

- [ ] Similarly, I'd like to add the same focus state we have for the inputs in the Add table to the search field. Please add `border: 1px solid #638699; box-shadow: 0 0 0 1px #638699;` to **#file-upload-types .file-upload-types-content .file-upload-types-table .search-box input:focus**

**Comment by jaredatch** [comment]
@mattbrett when you get a chance, please pull down last adjustments and see if this task is done done :)

**Comment by mattbrett** [comment]
@jaredatch @sanzeeb3 Nope, still some changes that need addressed.

- [ ] In the alert box at the top, there's an extra space between the lines. Should be a single line break, not two.

<img width="769" alt="CleanShot 2020-09-01 at 10 34 30@2x" src="https://user-images.githubusercontent.com/868109/91886878-d1310680-ec3e-11ea-82ce-25dec0a6a23d.png">

- [ ] **#file-upload-types .file-upload-types-content .file-upload-types-table .table-container:nth-of-type(2) table** Add `position: relative;`

- [ ] You added the text-align: right; on the wrong column. You applied it to the extension input field, but it was supposed to be on the last column that contains the trash and plus icons. Please refer to the screenshot above to see how it should look.

- [ ] Tooltip placement is still off vertically. Change margin of **.file-upload-types-info .tooltiptext** to `-19px 0 0 10px`.

<img width="435" alt="CleanShot 2020-09-01 at 10 31 50@2x" src="https://user-images.githubusercontent.com/868109/91886889-d68e5100-ec3e-11ea-99bc-ad0729758de1.png">

**Comment by mattbrett** [comment]
@jaredatch Also, this isn't a design change, but I noticed the page title (in the browser tab) is Settings. Shouldn't it be File Upload Types?

**Comment by sanzeeb3** [comment]
Thanks for checking, Matt. I'll make the required changes.

**Comment by sanzeeb3** [comment]
@mattbrett Could you please pull the latest changes and see? I'm unsure about the look of the notice with a single line break. If there's anything that needs a change, please let me know.

**Comment by mattbrett** [comment]
@sanzeeb3 Close!

- [ ] The box-shadow that's on the orange and blue buttons should only be visible on focus, not on hover. Only the background colour should change on hover.

- [ ] For the notice, let's use a single paragraph with a line break between them. Like this...

`<p><strong>File Upload Types now supports multiple MIME types for each file extension to improve file upload compatibility!<br><strong><a href="http://fileuploadtypes.test/wp-admin/options-general.php?page=file-upload-types&amp;multiple_mimes=enabled&amp;_wpnonce=7a9ddf656b">Enable multiple MIME types support</a> | <a href="https://wpforms.com/docs/how-to-allow-additional-file-upload-types/" target="_blank" rel="noopener noreferrer">Learn More</a></strong></strong></p>`

Everything else looks good!

**Comment by mattbrett** [comment]
@sanzeeb3 Looks great! We're done here. 🙂

**Comment by sanzeeb3** [comment]
@mattbrett great, thanks for all the way.
